### ISSUE TITLE
About "weighted_loss.txt"

### ISSUE THREAD

**Issue by BinhuiXie** [lianqing11/PyCDA#6]
Thanks for your great work, but I have a little confusion about the ``weighted_loss.txt``. I can't find the implementation of it in your project. And I wonder whether the descriptions below are correct.
- The weight is source class prior from source ground-truth label map.
- The weight is target class prior, then how can I get it?
- The weight is unchanged during the whole training process.

**Comment by lianqing11** [comment]
Hi, 
   Your first and thrd comments is right. The weight is source class prior and unchaned during training. I use terminal to create it so do not have the code about it. I will update the code about generating it.

Best regards,
Qing LIAN
